 - name: Play Web - Create apache directories and username in web servers
    hosts: all
       tasks:
      - name: ping my hosts
        ansible.builtin.ping:
      - name: print message
        ansible.builtin.debug:
         msg:hello world ansibel
          
          
         
