- name: Change file ownership, group and permissions
  hosts: all
 tasks:
   - name: name my file
     ansible.builtin.file:
     path: /ec2-user/home/myfile1.txt
     state: touch
     mode: '0644'
   
